title: 概率论与数理统计 2026
description: 2026 课程网站
theme: just-the-docs

url: https://zidalab.github.io/prob2026

aux_links:
  作业提交: http://172.21.19.12:3000/
  ZidaLab: https://zidalab.github.io

nav:
  - title: Home
    url: /
  - title: 开会
    url: /docs/meeting
  - title: 实验
    url: /docs/experiment
  - title: 写作与画图
    url: /docs/writing
  - title: 培训
    url: /docs/training
  - title: 其他
    url: /docs/misc
